### ISSUE TITLE
大佬这个只弹出视频已经刷完了

### ISSUE THREAD

**Issue by dadadio** [dzj0821/ChaoXingAutoPlayVideo#2]
要怎么改呢

**Comment by dzj0821** [comment]
弹出视频刷完了有两种情况
1、脚本没有获取到课程列表，你需要确认URL为*.chaoxing.com/mycourse/studentstudy*形式，左侧是课程内容，右侧是课程列表
2、默认的脚本文件开启了jump_one_task选项，如果开启了这个选项，脚本将自动跳过所有任务数为1的章节，任务数就是课程列表中每个章节前面的橙色圆圈里的数字

如果上面2种情况都不适用，请将页面截图给我，最好可以提供网页的源代码（右键——查看源代码），以便我更好的分析问题_(:3」∠)_

**Comment by dzj0821** [comment]
我更新了脚本，增加了更多提示信息，你可以使用最新脚本检查问题出现的原因

**Comment by dadadio** [comment]
已经解决了 大佬辛苦
