### ISSUE TITLE
出现问题求解

### ISSUE THREAD

**Issue by sakura-love** [dzj0821/ChaoXingAutoPlayVideo#3]
![20181115185125](https://user-images.githubusercontent.com/34211533/48548289-8c23cf00-e907-11e8-9a57-922bf699611a.png)

**Comment by sakura-love** [comment]
$ is not define这样的问题有多处以及$和 (   
![20181115185635](https://user-images.githubusercontent.com/34211533/48548549-34d22e80-e908-11e8-94a9-4236c48d5dc8.png)
i      temp     ) is already defined

**Comment by dzj0821** [comment]
这些警告和错误对脚本运行没有影响，产生的原因是油猴编辑器没有检测到jquery库，实际上我已经在@require中包含了jquery
如果不能使用/出现问题请描述出现时具体情况，最好能提供出现问题时的截图_(:3」∠)_

**Comment by sakura-love** [comment]
![20181115190042](https://user-images.githubusercontent.com/34211533/48548789-d6f21680-e908-11e8-96e9-042eb9eba527.png)

**Comment by dzj0821** [comment]
![qq 20181115190444](https://user-images.githubusercontent.com/36768960/48548947-597ad600-e909-11e8-87fb-c55ba308a581.jpg)
这些报错似乎都是网页本身的报错，跟脚本似乎没有关系？如果不能使用请反馈下具体情况

**Comment by sakura-love** [comment]
![20181115191230](https://user-images.githubusercontent.com/34211533/48549330-6ea43480-e90a-11e8-864a-cc3cd65143ca.png)就像这样，，，没有反应

**Comment by dzj0821** [comment]
你点击油猴上的开始自动答题了吗？如果依然没有反应，点击之后再把完整的控制台截图给我

**Comment by sakura-love** [comment]
点击了，并没有反应，然后这个完整的控制台是指的哪一部分的控制台呢

**Comment by dzj0821** [comment]
浏览器按下F12以后的Console标签下的内容

**Comment by sakura-love** [comment]
![20181115193005](https://user-images.githubusercontent.com/34211533/48550184-fbe88880-e90c-11e8-8367-557194fde6f6.png)
![Uploading 20181115193039.png…]()

**Comment by sakura-love** [comment]
![20181115193005](https://user-images.githubusercontent.com/34211533/48550377-8630ec80-e90d-11e8-9d69-3c742e8dc1c5.png)

**Comment by sakura-love** [comment]
![20181115193039](https://user-images.githubusercontent.com/34211533/48550394-91841800-e90d-11e8-9143-6d8a6b228d79.png)

**Comment by dzj0821** [comment]
![qq 20181115193455](https://user-images.githubusercontent.com/36768960/48550425-b082aa00-e90d-11e8-8d93-fe30c3ca6a80.jpg)
类似这样的输出只有这一条吗？如果是，麻烦你观察一下页面运行情况和我下面说的是否一致：
点击“开始自动刷题”后，页面会瞬间跳转到最上方且有任务未完成的章节，等待3秒后跳转到章节测验标签页，再等待3秒后在控制台输出题目信息，随后每5秒查询一次题目答案并选择

**Comment by sakura-love** [comment]
![111](https://user-images.githubusercontent.com/34211533/48550856-ce9cda00-e90e-11e8-9737-829c59d657ad.png)
就这样停下来了，不过上面说的跳转到章节测试标签页还是有，但是后面输出信息就没有了

**Comment by dzj0821** [comment]
![qq 20181115195754](https://user-images.githubusercontent.com/36768960/48551541-c80f6200-e910-11e8-8c25-a32c7c442636.png)
 你点下userscript报错的这个位置截图下 之前眼瞎了没看到= =

**Comment by sakura-love** [comment]
![112](https://user-images.githubusercontent.com/34211533/48551776-7915fc80-e911-11e8-92f1-425b151ec456.png)

**Comment by sakura-love** [comment]
![113](https://user-images.githubusercontent.com/34211533/48551795-829f6480-e911-11e8-816a-3853e02801cd.png)

**Comment by sakura-love** [comment]
![114](https://user-images.githubusercontent.com/34211533/48551804-8a5f0900-e911-11e8-9c80-312d6bdea9ca.png)

**Comment by dzj0821** [comment]
![qq 20181115200433](https://user-images.githubusercontent.com/36768960/48551863-b1b5d600-e911-11e8-8db6-2de9703ea311.png)
点击这一行呢
如果方便的话可以留个联系方式远程看下吗？

**Comment by sakura-love** [comment]
![115](https://user-images.githubusercontent.com/34211533/48551993-15400380-e912-11e8-9184-ddc5894a1f9c.png)
QQ:987792207

**Comment by dzj0821** [comment]
问题已解决，是因为浏览器安装了其他拓展，其他拓展在页面上添加了iframe，脚本82行调用$("iframe").contents()时发生了针对其他iframe的跨域访问导致报错
